# Generated by Django 4.1.1 on 2023-10-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_blogs_blog_alter_blog_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blog',
            table='blog',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
