# Generated by Django 4.1.1 on 2023-10-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_blog_table_alter_category_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='blog_images/'),
        ),
    ]
