# Generated by Django 4.1.1 on 2023-10-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_blog_created_at_blog_published_at_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=None),
        ),
    ]
