# Generated by Django 4.1.1 on 2023-10-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_blog_published_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='', upload_to='trident_images/')),
                ('alt_text', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 't_images',
            },
        ),
    ]
