# Generated by Django 4.1.1 on 2024-01-06 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
