# Generated by Django 4.1.1 on 2024-01-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_payments_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
