# Generated by Django 4.1.1 on 2024-01-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_payments_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='user_id',
            new_name='user',
        ),
    ]
