# Generated by Django 4.1.1 on 2024-01-27 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_usermanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserManager',
        ),
    ]
